#!/usr/bin/env python

import sys

def check_winning_numbers(chosen_numbers):
    winning_numbers = [9, 8, 10, 24, 75, 9]  # Placeholder for winning numbers
    bonus_number = winning_numbers[-1]

    if chosen_numbers == winning_numbers[:-1]:
        print("--> Congratulations! You have won the Jackpot!")
    else:
        print("--> Sorry, better luck next time.")

    print("Your chosen numbers: ", chosen_numbers)
    print("Winning numbers: ", winning_numbers)
    print("Bonus number: ", bonus_number)

if __name__ == "__main__":
    chosen_numbers = [int(arg) for arg in sys.argv[1:]]

    check_winning_numbers(chosen_numbers)
